/**
 * Generates derived assets for every raster image under `public/images`:
 *   - `<name>.thumb.webp` — small (max 480px) WebP used for thumbnail grids/strips.
 *   - a tiny blurred LQIP (base64 data URI) collected into
 *     `src/data/image-placeholders.ts` for blur-up progressive loading.
 *
 * Originals are left untouched. Re-run with `npm run optimize:images` whenever
 * images are added or changed.
 */
import { readdir, mkdir, writeFile } from "node:fs/promises";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const IMAGES_DIR = join(ROOT, "public", "images");
const PLACEHOLDER_OUT = join(ROOT, "src", "data", "image-placeholders.ts");

const SOURCE_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const THUMB_WIDTH = 480;
const THUMB_QUALITY = 72;
const LQIP_WIDTH = 24;
const LQIP_QUALITY = 40;

/** Recursively yield absolute file paths under `dir`. */
async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else yield full;
  }
}

/** Public-relative, forward-slashed key, e.g. `images/backgrounds/2.jpg`. */
function publicKey(absPath) {
  return relative(join(ROOT, "public"), absPath).split(sep).join("/");
}

function isGenerated(absPath) {
  return /\.thumb\.webp$/i.test(absPath);
}

async function main() {
  const placeholders = {};
  let thumbs = 0;
  let skipped = 0;

  for await (const file of walk(IMAGES_DIR)) {
    if (isGenerated(file)) continue;
    if (!SOURCE_EXTS.has(extname(file).toLowerCase())) {
      skipped += 1;
      continue;
    }

    const key = publicKey(file);
    const thumbPath = file.replace(/\.[^.]+$/, ".thumb.webp");

    try {
      await mkdir(dirname(thumbPath), { recursive: true });
      await sharp(file)
        .resize({ width: THUMB_WIDTH, withoutEnlargement: true })
        .webp({ quality: THUMB_QUALITY })
        .toFile(thumbPath);
      thumbs += 1;

      const lqip = await sharp(file)
        .resize({ width: LQIP_WIDTH })
        .webp({ quality: LQIP_QUALITY })
        .toBuffer();
      placeholders[key] = `data:image/webp;base64,${lqip.toString("base64")}`;
    } catch (err) {
      console.warn(`! Skipped ${key}: ${err.message}`);
    }
  }

  const sortedKeys = Object.keys(placeholders).sort();
  const entries = sortedKeys
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(placeholders[k])},`)
    .join("\n");

  const banner =
    "// AUTO-GENERATED by scripts/optimize-images.mjs. Do not edit by hand.\n" +
    "// Maps a public-relative image path to a tiny blurred placeholder data URI.\n" +
    "// A key present here also has a sibling `<name>.thumb.webp` thumbnail.\n";

  const out = `${banner}\nexport const IMAGE_PLACEHOLDERS: Record<string, string> = {\n${entries}\n};\n`;

  await writeFile(PLACEHOLDER_OUT, out, "utf8");

  console.log(
    `Done: ${thumbs} thumbnails, ${sortedKeys.length} placeholders, ${skipped} non-raster skipped.`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
